# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a118d14c4f75a40f19f2331724cc23948b78dc826a4c160984db972b69508fbbf073b0413fd17d5f9f8dcc3883c49442f964eac21a7a00036ef7a835369e064

test:
  secret_key_base: fd20d45d4b843db3b0eb5c9ebc190bc90b5e24ddb0273649dde4e3a006ba47130c7934c989b386c899d6326f176feed94f931cd7f6e3fc02c36c71f9ace7d1aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
